### ISSUE TITLE
Who to get value from a FieldTable

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sozu-proxy/amq-protocol#12]
Hi !

Thanks for developing the library ! it's awesome job !
I'm currently taking a look to get headers properties - like `x-count` on messages.
I cannot achieve it, the FieldTable does not implement BTreeMap ?

Thanks
Marc-Antoine

**Comment by Keruspe** [comment]
Hi,

You're right, that's a regression from 2.0. You can still access the contents by iterating on the FieldTable but yeah, I'll sure add a method to access the innter BTreeMap

**Comment by Keruspe** [comment]
Fixed in amq-protocol-types 2.1.1

**Comment by MarcAntoine-Arnaud** [comment]
Awesome ! very quick ;-)

**Comment by MarcAntoine-Arnaud** [comment]
Can we do something similar on a `FieldArray` ? maybe adding the iterator on it ?
Thanks
Marc-Antoine

**Comment by Keruspe** [comment]
You can use as_slice on FieldArray

**Comment by MarcAntoine-Arnaud** [comment]
It's not in the documentation: https://docs.rs/amq-protocol-types/2.1.0/amq_protocol_types/struct.FieldArray.html
And for me rustc mentionned it as in private...

Does I miss something ?

**Comment by Keruspe** [comment]
Oh, right, my bad.

Fixed in 2.1.2
