### ISSUE TITLE
Panic when parse uri

### ISSUE THREAD

**Issue by andreevlex** [sozu-proxy/amq-protocol#17]
Hello.

Panic this line:
https://github.com/sozu-proxy/amq-protocol/blob/master/uri/src/lib.rs#L110

ver. uri crate 3.1.0.

if set uri string
`amqp://127.0.0.1:5672`

but not panic if set
`amqp://127.0.0.1:5672/%2f`

**Comment by Keruspe** [comment]
Nice find, thanks!
